[env:esp32dev]
platform = espressif32
framework = espidf
board = esp32dev
board_build.flash_size = 4MB
monitor_speed = 460800
build_flags = -Icomponents/esp32-csi-tool/_components
board_build.sdkconfig_options = CONFIG_ESP_CONSOLE_UART_BAUDRATE=460800;CONFIG_ESPTOOLPY_MONITOR_BAUD=460800
